version: '3'
services:
  db:
    image: mysql:8
    #volumes: 
    # Make the database persistent
    #  #- "/tmp/db:/var/lib/mysql"
    # Init the db from a sample sql file
    #  - "./db-init:/docker-entrypoint-initdb.d"
    ports: ["3306:3306"]
    environment:
      MYSQL_DATABASE: netwiki_shop
      MYSQL_ROOT_PASSWORD: root
    network_mode: bridge


  web:
    build: .
    image: shaftmx/shopping-lists
    #command: sleep 3600
    links: [db]
    depends_on: [db]
    ports:
      - "8000:80"
      - "5000:5000"
    #volumes: 
    #  - "./extra/:/legacy"
    environment:
      DB_NAME: netwiki_shop
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
    network_mode: bridge

